### ISSUE TITLE
SPU build is broken (tested with Ubuntu 10.10)

### ISSUE THREAD

**Issue by bvernoux** [HACKERCHANNEL/ps3chain#2]
Hi,

I have added all software needed by the tool chain:
sudo apt-get install autoconf automake bison flex gcc make wget git libppl0.10-dev libcloog-ppl-dev libelf-dev libncurses5-dev texinfo build-essential

With good exports in ~/.bashrc
export PS3DEV=/media/LinuxDev/ps3dev
export PATH=$PATH:$PS3DEV/bin
export PATH=$PATH:$PS3DEV/ppu/bin
export PATH=$PATH:$PS3DEV/spu/bin
export PSL1GHT=/media/LinuxDev/PSL1GHT/build

PPU build just worked fine but SPU build fail also tested with ps3toolchain with same error (seems linked to a problem with new lib 1.18.0).

See details hereafter:
/media/LinuxDev/ps3dev/spu/bin/spu-gcc -B/media/LinuxDev/ps3dev/build_newlib/spu/newlib/ -isystem /media/LinuxDev/ps3dev/build_newlib/spu/newlib/targ-include -isystem /media/LinuxDev/ps3dev/newlib-1.18.0/newlib/libc/include -B/media/LinuxDev/ps3dev/build_newlib/spu/libgloss/spu -L/media/LinuxDev/ps3dev/build_newlib/spu/libgloss/libnosys -L/media/LinuxDev/ps3dev/newlib-1.18.0/libgloss/spu    -DPACKAGE_NAME=\"newlib\" -DPACKAGE_TARNAME=\"newlib\" -DPACKAGE_VERSION=\"1.18.0\" -DPACKAGE_STRING=\"newlib\ 1.18.0\" -DPACKAGE_BUGREPORT=\"\" -I. -I/media/LinuxDev/ps3dev/newlib-1.18.0/newlib/libc/argz -D_POSIX_MODE -DREENTRANT_SYSCALLS_PROVIDED -DMISSING_SYSCALL_NAMES -ffunction-sections -fdata-sections  -DMISSING_SYSCALL_NAMES -fno-builtin      -g -O2 -c -o lib_a-argz_add_sep.o `test -f 'argz_add_sep.c' || echo '/media/LinuxDev/ps3dev/newlib-1.18.0/newlib/libc/argz/'`argz_add_sep.c
/tmp/ccfYfJ8R.s: Assembler messages:
/tmp/ccfYfJ8R.s:10: Error: unknown pseudo-op: `.cfi_sections'
make[5]: *** [lib_a-dummy.o] Erreur 1
make[5]: *** Attente des tâches non terminées....
/tmp/cchmA4FS.s: Assembler messages:
/tmp/cchmA4FS.s:10: Error: unknown pseudo-op:`.cfi_sections'
/tmp/cchmA4FS.s:19: Error: unknown pseudo-op: `.cfi_startproc'
/tmp/cchmA4FS.s:28: Error: unknown pseudo-op:`.cfi_offset'
/tmp/cchmA4FS.s:31: Error: unknown pseudo-op: `.cfi_offset'
/tmp/cchmA4FS.s:42: Error: unknown pseudo-op:`.cfi_def_cfa_offset'
/tmp/cchmA4FS.s:68: Error: unknown pseudo-op: `.cfi_offset'
/tmp/cchmA4FS.s:69: Error: unknown pseudo-op:`.cfi_offset'
/tmp/cchmA4FS.s:147: Error: unknown pseudo-op: `.cfi_endproc'
make[5]: *** [lib_a-argz_add_sep.o] Erreur 1
/tmp/cc2NpIEV.s: Assembler messages:
/tmp/cc2NpIEV.s:10: Error: unknown pseudo-op:`.cfi_sections'
/tmp/cc2NpIEV.s:19: Error: unknown pseudo-op: `.cfi_startproc'
/tmp/cc2NpIEV.s:25: Error: unknown pseudo-op:`.cfi_offset'
/tmp/cc2NpIEV.s:29: Error: unknown pseudo-op: `.cfi_offset'
/tmp/cc2NpIEV.s:32: Error: unknown pseudo-op:`.cfi_offset'
/tmp/cc2NpIEV.s:40: Error: unknown pseudo-op: `.cfi_offset'
/tmp/cc2NpIEV.s:41: Error: unknown pseudo-op:`.cfi_offset'
/tmp/cc2NpIEV.s:47: Error: unknown pseudo-op: `.cfi_def_cfa_offset'
/tmp/cc2NpIEV.s:53: Error: unknown pseudo-op:`.cfi_offset'
/tmp/cc2NpIEV.s:127: Error: unknown pseudo-op: `.cfi_endproc'
make[5]: **\* [lib_a-argz_add.o] Erreur 1

**Comment by cebash** [comment]
I've got that problem too under an ubuntu x86_64 an a virtual boxed ubuntu 32bit. 

But ooPo has just fixed it on ps3toolchain (see last commits).

**Comment by bvernoux** [comment]
Ok just tried it again yesterday and it worked now.
